### ISSUE TITLE
Potential security issue in src/tool_operate.c: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [siva-msft/curl#37]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

1 instance of this defect were found in the following locations:
---
**Instance 1**
File : `src/tool_operate.c` 
Function: `post_per_transfer` 
https://github.com/siva-msft/curl/blob/3c26766b1c420f0920e90b4453d14e7b5fc01cdf/src/tool_operate.c#L2141
Code extract:

```cpp
          curl_easy_getinfo(easy, CURLINFO_PRIVATE, (void *)&ended);
          curl_multi_remove_handle(multi, easy);

          result = post_per_transfer(global, ended, result, &retry); <------ HERE
          if(retry)
            continue;
```

**How can I fix it?** 
Correct reference usage found in `src/tool_operate.c` at line `2212`.
https://github.com/siva-msft/curl/blob/3c26766b1c420f0920e90b4453d14e7b5fc01cdf/src/tool_operate.c#L2212
Code extract:

```cpp
    /* store the result of the actual transfer */
    returncode = result;

    result = post_per_transfer(global, per, result, &retry); <------ HERE
    if(retry)
      continue;
```

**Comment by siva-msft** [comment]
assign.
